import React from "react";

function AboutMe() {
  return <div className="">
    <div>salom</div>
    <div>salom</div>
    <div>salom</div>
    <div>salom</div>
    <div>salom</div>
    <div>salom</div>
    <div>salom</div>
    <div>salom</div>
    <div>salom</div>
    <div>salom</div>
    <div>salom</div>
    <div>salom</div>
    <div>salom</div>
    <div>salom</div>
    <div>salom</div>
    <div>salom</div>
    <div>salom</div>
    <div>salom</div>
    <div>salom</div>
    <div>salom</div>
    <div>salom</div>
    <div>salom</div>
    <div>salom</div>
    <div>salom</div>
    <div>salom</div>
    <div>salom</div>
    <div>salom</div>
    <div>salom</div>
    <div>salom</div>
    <div>salom</div>
    <div>salom</div>
    <div>salom</div>
    <div>salom</div>
    <div>salom</div>
    <div>salom</div>
    <div>salom</div>
    <div>salom</div>
    <div>salom</div>
    <div>salom</div>
    <div>salom</div>
    <div>salom</div>
    <div>salom</div>
    <div>salom</div>
    <div>salom</div>
    <div>salom</div>
    <div>salom</div>
    <div>salom</div>
    <div>salom</div>
    <div>salom</div>
    <div>salom</div>
    <div>salom</div>
    <div>salom</div>
    <div>salom</div>
    <div>salom</div>
    <div>salom</div>
    <div>salom</div>
    <div>salom</div>
    <div>salom</div>
    <div>salom</div>
    <div>salom</div>
    <div>salom</div>
    <div>salom</div>
    <div>salom</div>
    <div>salom</div>
    <div>salom</div>
    <div>salom</div>
    <div>salom</div>
    <div>salom</div>
    <div>salom</div>
    <div>salom</div>
    <div>salom</div>
    <div>salom</div>
    <div>salom</div>
    <div>salom</div>
    <div>salom</div>
    <div>salom</div>
    <div>salom</div>
    <div>salom</div>
    <div>salom</div>
    <div>salom</div>
    <div>salom</div>
    <div>salom</div>
    <div>salom</div>
    <div>salom</div>
    <div>salom</div>
    <div>salom</div>
  </div>;
}

export default AboutMe;
