import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import { cn } from "@/lib/utils";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Khusan Mirobidov",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark:bg-black">
      <body
        className={cn("dark flex flex-col relative scrollbar md:h-screen  min-h-screen md:overflow-hidden md:max-h-screen", geistSans.variable, geistMono.variable, "antialiased")}
      >
        <Header className="sticky top-0" />
        <main className="flex-grow md:overflow-hidden">{children}</main>
        <Footer />
      </body>
    </html >
  );
}
