import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import { Toaster } from "@/components/ui/toaster";
import Footer from "@/components/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Khusan Mirobidov",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark:bg-black">
      <body
        className={`
          dark flex flex-col h-[100vh] overflow-hidden max-h-[100vh] ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        <div className="flex-grow">{children}</div>
        <Footer />
        {/* <ClientLayout /> */}
        <Toaster />
      </body>
    </html>
  );
}
